const DATA={conditions:window.TCM_CONDITIONS,points:window.TCM_POINTS,herbs:window.TCM_HERBS,formulas:window.TCM_FORMULAS};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state=JSON.parse(localStorage.getItem('mastery-v2')||'{"reviews":0,"correct":0,"attempts":0,"caseStep":0}');
function save(){localStorage.setItem('mastery-v2',JSON.stringify(state))}
function go(id){$$('.view').forEach(x=>x.classList.toggle('active',x.id===id));$$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.v===id));scrollTo(0,0);if(id==='conditions')renderConditions();if(id==='points')renderPoints();if(id==='herbs')renderHerbs();if(id==='formulas')renderFormulas();if(id==='study')newStudy();if(id==='case')renderCase();if(id==='master')nextMaster()}
function installHelp(){alert('Öppna sidan i Safari → Dela → Lägg till på hemskärmen. Studieframsteg sparas lokalt på mobilen.')}
let selectedCondition=0;
function renderConditions(){let q=($('#conditionSearch')?.value||'').toLowerCase();let arr=DATA.conditions.filter(x=>(x.title+x.english+x.patterns.join(' ')).toLowerCase().includes(q));$('#conditionList').innerHTML=arr.map(x=>`<button class="item ${x.chapter===selectedCondition+1?'selected':''}" onclick="selectCondition(${x.chapter-1})"><b>Kapitel ${x.chapter} · ${x.title}</b><small>${x.english} · ${x.patterns.slice(0,2).join(' / ')}</small></button>`).join('');renderConditionDetail()}
function selectCondition(i){selectedCondition=i;renderConditions()}
function renderConditionDetail(){let x=DATA.conditions[selectedCondition];$('#conditionDetail').innerHTML=`<span class="badge">Kapitel ${x.chapter}</span><h2>${x.title}</h2><p class="muted">${x.english}</p><h3>Mönster att differentiera</h3><div class="chips">${x.patterns.map(p=>`<span class="chip">${p}</span>`).join('')}</div><div class="facts"><div class="fact"><small>Frågor med hög informationsvinst</small>• Debut och tidsförlopp<br>• Förvärrande och lindrande faktorer<br>• Energi, sömn och aptit<br>• Avföring, urin och törst<br>• Smärtans plats och karaktär<br>• Läkemedel, graviditet och rödflaggor</div><div class="fact"><small>Obligatorisk arbetsgång</small>1. Säkerhet och biomedicinsk differential<br>2. Samla huvud- och följdsymtom<br>3. Bedöm tunga och puls i sitt sammanhang<br>4. Väg fynd för och emot varje mönster<br>5. Formulera mekanism<br>6. Formulera behandlingsprincip<br>7. Välj verktyg och följ upp</div><div class="fact"><small>Tunga och puls</small>Dokumentera observationen först. Tolka först därefter och ange vad som talar emot din hypotes.</div><div class="fact"><small>Uppföljning</small>Förändring, tolerans, nya rödflaggor, om hypotesen håller och när behandlingen ska avslutas eller omvärderas.</div></div><div class="safety">Säkerhet före TCM: uteslut akuta eller allvarliga orsaker, kontrollera läkemedel, graviditet, ålder, dehydrering, blödning och andra relevanta rödflaggor.</div><p class="source">Maciocia, The Practice of Chinese Medicine, kapitel ${x.chapter} · Pedagogisk syntes, inte ordagrann boktext.</p>`}
let channel='Alla',selectedPoint=0;
function initChannels(){let cs=['Alla',...new Set(DATA.points.map(x=>x.channel))];$('#channelFilters').innerHTML=cs.map(c=>`<button onclick="channel='${c}';renderPoints()">${c}</button>`).join('')}
function renderPoints(){let q=($('#pointSearch')?.value||'').toLowerCase();let arr=DATA.points.filter(x=>(channel==='Alla'||x.channel===channel)&& (x.id+x.name+x.channel).toLowerCase().includes(q));$('#pointList').innerHTML=arr.slice(0,120).map((x)=>`<button class="item" onclick="selectPoint('${x.id}')"><b>${x.id} ${x.name?'· '+x.name:''}</b><small>${x.channel}</small></button>`).join('')+(arr.length>120?`<p class="muted">Visar 120 av ${arr.length}. Sök mer specifikt.</p>`:'');renderPointDetail()}
function selectPoint(id){selectedPoint=DATA.points.findIndex(x=>x.id===id);renderPointDetail()}
function renderPointDetail(){let x=DATA.points[selectedPoint];$('#pointDetail').innerHTML=`<span class="badge">Seirin: ${x.channel}-meridianen</span><h2>${x.id} ${x.name?'· '+x.name:''}</h2><p class="muted">${x.channel}</p><div class="facts"><div class="fact"><small>Studieuppgift</small>Lär punktens namn, anatomiska region, palpationslandmärke, traditionella funktioner, närliggande riskstrukturer och vanliga förväxlingspunkter.</div><div class="fact"><small>Självtest</small>Kan du ange region, landmärke, närliggande punkt och en viktig säkerhetsrisk utan att titta?</div><div class="fact"><small>Jämför</small>Identifiera föregående och nästa punkt på meridianen samt en punkt från annan meridian i samma anatomiska region.</div><div class="fact"><small>Kapitelhänvisning</small>Seirin: ${x.channel}-meridianen</div></div><div class="safety">Nålriktning och djup ska verifieras i atlas och med handledare; appen ger inte invasiva instruktioner.</div><p class="source">Punktkodsystem: WHO:s standardnomenklatur för 361 klassiska punkter. Anatomisk detalj: verifiera i Seirins punktatlas.</p>`}
let selectedHerb=0;
function renderHerbs(){let q=($('#herbSearch')?.value||'').toLowerCase();let arr=DATA.herbs.map((x,i)=>({...x,i})).filter(x=>(x.pinyin+x.category+x.pattern+x.functions).toLowerCase().includes(q));$('#herbList').innerHTML=arr.map(x=>`<button class="item ${x.i===selectedHerb?'selected':''}" onclick="selectedHerb=${x.i};renderHerbs()"><b>${x.pinyin}</b><small>${x.category} · ${x.pattern}</small></button>`).join('');renderHerbDetail()}
function renderHerbDetail(){let x=DATA.herbs[selectedHerb];let similar=DATA.herbs.filter(h=>h.category.split(',')[0]===x.category.split(',')[0]&&h.pinyin!==x.pinyin).slice(0,4);$('#herbDetail').innerHTML=`<span class="badge gold">${x.category}</span><h2>${x.pinyin}</h2><div class="facts"><div class="fact"><small>Mönsterlogik</small>${x.pattern}</div><div class="fact"><small>Funktionsområden</small>${x.functions}</div><div class="fact"><small>Jämför med</small>${similar.map(h=>h.pinyin).join(', ')||'Sök inom samma kategori'}</div><div class="fact"><small>Dosering</small>Verifiera i fysisk bok; visas inte utan källkontroll</div></div><h3>Mästarfrågor</h3><div class="chips"><span class="chip">När väljs den?</span><span class="chip">När väljs den inte?</span><span class="chip">Vilken liknande ört är alternativ?</span><span class="chip">Hur påverkar beredningen?</span></div><div class="safety"><b>Säkerhet:</b> ${x.safety}. Kontrollera alltid läkemedel, graviditet, lever/njurfunktion, allergi, produktkvalitet och artidentitet.</div><p class="source">Materia Medica: kapitel enligt kategori · Pedagogisk översikt.</p>`}
let selectedFormula=0;
function renderFormulas(){let q=($('#formulaSearch')?.value||'').toLowerCase();let arr=DATA.formulas.map((x,i)=>({...x,i})).filter(x=>(x.name+x.category+x.pattern+x.ingredients.join(' ')).toLowerCase().includes(q));$('#formulaList').innerHTML=arr.map(x=>`<button class="item ${x.i===selectedFormula?'selected':''}" onclick="selectedFormula=${x.i};renderFormulas()"><b>${x.name}</b><small>${x.category} · ${x.pattern}</small></button>`).join('');renderFormulaDetail()}
function renderFormulaDetail(){let x=DATA.formulas[selectedFormula];$('#formulaDetail').innerHTML=`<span class="badge gold">${x.category}</span><h2>${x.name}</h2><p>${x.pattern}</p><h3>Ingrediensstruktur</h3><div class="chips">${x.ingredients.map((h,i)=>`<span class="chip">${i===0?'Kejsarkandidat: ':''}${h}</span>`).join('')}</div><div class="facts"><div class="fact"><small>Analysera roller</small>Identifiera kejsare, minister, assistent och budbärare utifrån formelns behandlingsprincip.</div><div class="fact"><small>Ta bort en ört</small>Förklara vilken del av riktning, balans, säkerhet eller symptomprofil som försvagas.</div><div class="fact"><small>Jämför</small>Hitta en närliggande formel i samma kategori och förklara det avgörande skiljetecknet.</div><div class="fact"><small>Omvärdera</small>Ange fynd som skulle göra att formeln inte längre passar.</div></div><div class="safety">Utbildningspost. Dosförhållanden, substitutioner och klinisk användning måste verifieras i boken och av kvalificerad handledare.</div><p class="source">Chinese Herbal Formulas and Applications: kapitel enligt formelkategori · Ingrediensnamnen är studieöversikt; proportioner verifieras i boken.</p>`}
let studyFirst=true,currentCard=null;
function allCards(){let a=[];DATA.conditions.forEach(x=>a.push({type:'Diagnostik',q:`Vilka fyra mönster ska differentieras i kapitel ${x.chapter} om ${x.title}?`,a:x.patterns.join(', ')}));DATA.herbs.forEach(x=>a.push({type:'Ört',q:`Förklara när ${x.pinyin} kan övervägas traditionellt och nämn en säkerhetsfråga.`,a:`Kategori: ${x.category}. Mönster: ${x.pattern}. Säkerhet: ${x.safety}.`}));DATA.formulas.forEach(x=>a.push({type:'Formel',q:`Vilket mönster och vilken princip ligger bakom ${x.name}?`,a:`Mönster: ${x.pattern}. Kategori/princip: ${x.category}.`}));return a}
const CARDS=allCards();
function newStudy(){currentCard=CARDS[Math.floor(Math.random()*CARDS.length)];studyFirst=true;$('#studyBadge').textContent=currentCard.type;$('#studyQ').textContent=currentCard.q;$('#studyA').textContent=currentCard.a;$('#studyA').classList.add('hidden');$('#studyText').value=''}
function showStudyAnswer(){studyFirst=false;$('#studyA').classList.remove('hidden')}
function grade(n){state.attempts++;if(n===2&&studyFirst)state.correct++;state.reviews++;save();newStudy()}
function speakQuestion(){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance($('#studyQ').textContent))}
const cases=[{title:'Trötthet med matsmältningsbesvär',intro:'Trötthet efter mat, låg aptit och lösa avföringar.',patterns:['Mjälte-Qi-brist','Fukt som hindrar mitten','Lever-Qi invaderar Mjälten']},{title:'Återkommande huvudvärk',intro:'Huvudvärk med varierande plats och tydliga triggers.',patterns:['Lever-Yang stiger','Blod-brist','Blodstas','Slem-Fukt']},{title:'Sömnbesvär och oro',intro:'Svårt att somna, många tankar och hjärtklappningskänsla.',patterns:['Hjärta-Blod-brist','Hjärta-Yin-brist','Slem-Hetta','Hjärta–Njure disharmoni']},{title:'Hosta med slem',intro:'Hosta där färg, mängd och konsistens på slemmet varierar.',patterns:['Vind-Kyla','Vind-Hetta','Fukt-Slem','Slem-Hetta','Lung-Yin-brist']},{title:'Ländryggssmärta',intro:'Smärta som påverkas av rörelse, kyla och trötthet.',patterns:['Kyla-Fukt','Blodstas','Njure-Yang-brist','Njure-Yin-brist']}];let caseObj=cases[Math.floor(Math.random()*cases.length)],caseAnswers={};
function renderCase(){let s=state.caseStep||0;$('#caseTitle').textContent=caseObj.title;$('#caseSteps').innerHTML=['Säkerhet','Frågor','Mönster','Mekanism','Princip','Val','Uppföljning'].map((x,i)=>`<div class="step ${i<=s?'on':''}">${i+1}</div>`).join('');let c=$('#caseContent');if(s===0)c.innerHTML=`<span class="eyebrow">Säkerhet före teori</span><h2>${caseObj.intro}</h2><p>Beskriv vilka rödflaggor, läkemedel, graviditetsfrågor eller biomedicinska differentialer som måste kontrolleras.</p><textarea id="caseText"></textarea><button class="primary" onclick="caseNext($('#caseText').value.length>50)">Fortsätt</button>`;if(s===1)c.innerHTML=`<h2>Välj frågor med hög informationsvinst</h2>${['Debut och förlopp','Förvärrande/lindrande faktorer','Tunga och puls','Aptit, avföring, urin och törst','Sömn, stress och läkemedel'].map(x=>`<button class="option" onclick="this.classList.toggle('sel');caseAnswers['${x}']=true">${x}</button>`).join('')}<button class="primary" onclick="caseNext(Object.keys(caseAnswers).length>=4)">Visa fynd</button>`;if(s===2)c.innerHTML=`<h2>Differentiera mönster</h2><p class="answer">${caseObj.intro}</p>${caseObj.patterns.map((x,i)=>`<button class="option" onclick="this.classList.toggle('sel')">${x}</button>`).join('')}<textarea id="caseText" placeholder="Ange fynd för, fynd emot och saknad information…"></textarea><button class="primary" onclick="caseNext($('#caseText').value.length>100)">Fortsätt</button>`;if(s===3)c.innerHTML=`<h2>Bygg sjukdomsmekanismen</h2><textarea id="caseText" placeholder="Orsak → funktionsstörning → följd → symtom. Minst fyra länkar."></textarea><button class="primary" onclick="caseNext($('#caseText').value.length>120)">Fortsätt</button>`;if(s===4)c.innerHTML=`<h2>Formulera behandlingsprincip</h2><p>Skriv vad som ska åstadkommas utan att nämna punkter, örter eller formler.</p><textarea id="caseText"></textarea><button class="primary" onclick="caseNext($('#caseText').value.length>70)">Lås upp val</button>`;if(s===5)c.innerHTML=`<h2>Välj verktyg och försvara</h2><p>Använd punkt-, ört- och formelbiblioteken. Ange varför varje val följer principen och vilken säkerhetskontroll som krävs.</p><textarea id="caseText"></textarea><button class="primary" onclick="caseNext($('#caseText').value.length>120)">Uppföljning</button>`;if(s===6)c.innerHTML=`<h2>Stäng loopen</h2><div class="facts"><div class="fact"><small>Effekt</small>Vilka symtom och funktioner ska förändras?</div><div class="fact"><small>Säkerhet</small>Vilka biverkningar och interaktioner följs?</div><div class="fact"><small>Hypotes</small>Vad skulle falsifiera ditt mönster?</div><div class="fact"><small>Beslut</small>När avslutas, ändras eller hänvisas?</div></div><button class="primary" onclick="finishCase()">Slutför och skapa nytt fall</button>`}
function caseNext(ok){if(!ok)return alert('Utveckla resonemanget mer innan du går vidare.');state.caseStep=Math.min(6,(state.caseStep||0)+1);save();renderCase()}
function finishCase(){state.caseStep=0;caseAnswers={};caseObj=cases[Math.floor(Math.random()*cases.length)];save();renderCase()}
const masterQuestions=['Förklara skillnaden mellan att känna igen ett mönsternamn och att faktiskt ha differentierat mönstret.','Välj två närliggande Qi-tonika. Vilket fynd gör att du väljer den ena framför den andra?','Välj en formel och förklara kejsare, minister, assistent och budbärare utan att bara rabbla ingredienser.','Vilka fynd skulle få dig att överge din första TCM-hypotes i ett patientfall?','Hur skiljer du traditionell indikation, innehåll i kursbok, modern evidens och klinisk säkerhet?','Beskriv hur ett enda symtom kan uppstå ur minst tre olika sjukdomsmekanismer.','Välj tre punkter i samma anatomiska region och förklara hur du undviker sammanblandning och säkerhetsrisk.'];let masterIndex=0;
function nextMaster(){masterIndex=(masterIndex+1)%masterQuestions.length;$('#masterQ').textContent=masterQuestions[masterIndex];$('#masterText').value='';$('#masterHint').innerHTML='<b>Ett nivå-7-svar ska innehålla:</b> påstående, fynd för, fynd emot, alternativ hypotes, säkerhet och vad som skulle ändra beslutet.'}
function speakMaster(){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance($('#masterQ').textContent))}
initChannels();renderConditions();renderPoints();renderHerbs();renderFormulas();newStudy();renderCase();nextMaster();
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
